# Load a real Indian dataset (CSV) into Pandas DataFrame. Print: shape, dtypes, head(10).

In [25]:
import pandas as pd

In [4]:
df = pd.read_csv("india_state_2011.csv")

In [9]:
df.head(10)

,State_UT,Region,Population_2011,Literacy_Rate_2011,Source
0,Andaman and Nicobar Islands,South,380581,86.3,Office of the Registrar General and Census Com...
1,Andhra Pradesh,South,49386799,67.7,Office of the Registrar General and Census Com...
2,Arunachal Pradesh,North East,1383727,67.0,Office of the Registrar General and Census Com...
3,Assam,North East,31205576,73.2,Office of the Registrar General and Census Com...
4,Bihar,East,104099452,63.8,Office of the Registrar General and Census Com...
5,Chandigarh,North,1055450,86.4,Office of the Registrar General and Census Com...
6,Chhattisgarh,Central,25545198,71.0,Office of the Registrar General and Census Com...
7,Dadra and Nagar Haveli,West,343709,77.7,Office of the Registrar General and Census Com...
8,Daman and Diu,West,243247,87.1,Office of the Registrar General and Census Com...
9,Delhi,North,16787941,86.3,Office of the Registrar General and Census Com...

In [7]:
df1 = df.drop('Source', axis = 1)

In [10]:
df1.head(10)

,State_UT,Region,Population_2011,Literacy_Rate_2011
0,Andaman and Nicobar Islands,South,380581,86.3
1,Andhra Pradesh,South,49386799,67.7
2,Arunachal Pradesh,North East,1383727,67.0
3,Assam,North East,31205576,73.2
4,Bihar,East,104099452,63.8
5,Chandigarh,North,1055450,86.4
6,Chhattisgarh,Central,25545198,71.0
7,Dadra and Nagar Haveli,West,343709,77.7
8,Daman and Diu,West,243247,87.1
9,Delhi,North,16787941,86.3

In [11]:
df2 = df.drop(['Source', 'Region'], axis = 1)

In [12]:
df2.head(10)

                      State_UT  Population_2011  Literacy_Rate_2011
0  Andaman and Nicobar Islands           380581                86.3
1               Andhra Pradesh         49386799                67.7
2            Arunachal Pradesh          1383727                67.0
3                        Assam         31205576                73.2
4                        Bihar        104099452                63.8
5                   Chandigarh          1055450                86.4
6                 Chhattisgarh         25545198                71.0
7       Dadra and Nagar Haveli           343709                77.7
8                Daman and Diu           243247                87.1
9                        Delhi         16787941                86.3

df1.shape

In [15]:
df2. shape

(36, 3)

In [21]:
df1.dtypes

State_UT                  str
Region                    str
Population_2011         int64
Literacy_Rate_2011    float64
dtype: object

In [23]:
print(df["State_UT"].dtype)

str

In [24]:
print(df2.dtypes)

State_UT                  str
Population_2011         int64
Literacy_Rate_2011    float64
dtype: object

# Performing filter, groupby, merge, pivot_table.

In [12]:
import pandas as pd

In [15]:
# Filter states/UTs with literacy rates of 80% or higher
df = pd.read_csv('india_state_2011.csv')

In [6]:
df

,State_UT,Region,Population_2011,Literacy_Rate_2011,Source
0,Andaman and Nicobar Islands,South,380581,86.3,Office of the Registrar General and Census Com...
1,Andhra Pradesh,South,49386799,67.7,Office of the Registrar General and Census Com...
2,Arunachal Pradesh,North East,1383727,67.0,Office of the Registrar General and Census Com...
3,Assam,North East,31205576,73.2,Office of the Registrar General and Census Com...
4,Bihar,East,104099452,63.8,Office of the Registrar General and Census Com...
5,Chandigarh,North,1055450,86.4,Office of the Registrar General and Census Com...
6,Chhattisgarh,Central,25545198,71.0,Office of the Registrar General and Census Com...
7,Dadra and Nagar Haveli,West,343709,77.7,Office of the Registrar General and Census Com...
8,Daman and Diu,West,243247,87.1,Office of the Registrar General and Census Com...
9,Delhi,North,16787941,86.3,Office of the Registrar General and Census Com...
10,Goa,West,1458545,87.4,Office of the Registrar General and Census Com...
11,Gujarat,West,60439692,79.3,Office of the Registrar General and Census Com...
12,Haryana,North,25351462,76.6,Office of the Registrar General and Census Com...
13,Himachal Pradesh,North,6864602,83.8,Office of the Registrar General and Census Com...
14,Jammu and Kashmir,North,12267013,68.7,Office of the Registrar General and Census Com...
15,Jharkhand,East,32988134,67.6,Office of the Registrar General and Census Com...
16,Karnataka,South,61095297,75.6,Office of the Registrar General and Census Com...
17,Kerala,South,33406061,93.9,Office of the Registrar General and Census Com...
18,Lakshadweep,South,64473,92.3,Office of the Registrar General and Census Com...
19,Madhya Pradesh,Central,72626809,70.6,Office of the Registrar General and Census Com...
20,Maharashtra,West,112374333,82.9,Office of the Registrar General and Census Com...
21,Manipur,North East,2855794,79.8,Office of the Registrar General and Census Com...
22,Meghalaya,North East,2966889,75.5,Office of the Registrar General and Census Com...
23,Mizoram,North East,1097206,91.6,Office of the Registrar General and Census Com...
24,Nagaland,North East,1978502,80.1,Office of the Registrar General and Census Com...
25,Odisha,East,41974218,73.5,Office of the Registrar General and Census Com...
26,Puducherry,South,1247953,86.5,Office of the Registrar General and Census Com...
27,Punjab,North,27743338,76.7,Office of the Registrar General and Census Com...
28,Rajasthan,North,68548437,67.1,Office of the Registrar General and Census Com...
29,Sikkim,North East,610577,82.2,Office of the Registrar General and Census Com...
30,Tamil Nadu,South,72147030,80.3,Office of the Registrar General and Census Com...
31,Telangana,South,35193978,66.5,Office of the Registrar General and Census Com...
32,Tripura,North East,3673917,87.8,Office of the Registrar General and Census Com...
33,Uttar Pradesh,North,199812341,69.7,Office of the Registrar General and Census Com...
34,Uttarakhand,North,10086292,79.6,Office of the Registrar General and Census Com...
35,West Bengal,East,91276115,77.1,Office of the Registrar General and Census Com...

In [9]:
df1 = df[df['Literacy_Rate_2011'] >= 80 ]

In [10]:
df1

,State_UT,Region,Population_2011,Literacy_Rate_2011,Source
0,Andaman and Nicobar Islands,South,380581,86.3,Office of the Registrar General and Census Com...
5,Chandigarh,North,1055450,86.4,Office of the Registrar General and Census Com...
8,Daman and Diu,West,243247,87.1,Office of the Registrar General and Census Com...
9,Delhi,North,16787941,86.3,Office of the Registrar General and Census Com...
10,Goa,West,1458545,87.4,Office of the Registrar General and Census Com...
13,Himachal Pradesh,North,6864602,83.8,Office of the Registrar General and Census Com...
17,Kerala,South,33406061,93.9,Office of the Registrar General and Census Com...
18,Lakshadweep,South,64473,92.3,Office of the Registrar General and Census Com...
20,Maharashtra,West,112374333,82.9,Office of the Registrar General and Census Com...
23,Mizoram,North East,1097206,91.6,Office of the Registrar General and Census Com...
24,Nagaland,North East,1978502,80.1,Office of the Registrar General and Census Com...
26,Puducherry,South,1247953,86.5,Office of the Registrar General and Census Com...
29,Sikkim,North East,610577,82.2,Office of the Registrar General and Census Com...
30,Tamil Nadu,South,72147030,80.3,Office of the Registrar General and Census Com...
32,Tripura,North East,3673917,87.8,Office of the Registrar General and Census Com...

In [20]:
#GroupBy using Region
group_by_region = df.groupby("Region").count()

In [21]:
group_by_region

            State_UT  Population_2011  Literacy_Rate_2011  Source
Region
Central            2                2                   2       2
East               4                4                   4       4
North              9                9                   9       9
North East         8                8                   8       8
South              8                8                   8       8
West               5                5                   5       5

In [35]:
#groupby using region and population using sum() function 
df.groupby("Region")["Population_2011"].sum()

Region
Central        98172007
East          270337919
North         368516876
North East     45772188
South         252922172
West          174859526
Name: Population_2011, dtype: int64

In [36]:
#groupby using region and population using mean() function 
df.groupby("Region")["Population_2011"].mean()

Region
Central       4.908600e+07
East          6.758448e+07
North         4.094632e+07
North East    5.721524e+06
South         3.161527e+07
West          3.497191e+07
Name: Population_2011, dtype: float64

In [37]:
#groupby using region and population using min() function 
df.groupby("Region")["Population_2011"].min()

Region
Central       25545198
East          32988134
North          1055450
North East      610577
South            64473
West            243247
Name: Population_2011, dtype: int64

In [38]:
#groupby using region and population using max() function 
df.groupby("Region")["Population_2011"].max()

Region
Central        72626809
East          104099452
North         199812341
North East     31205576
South          72147030
West          112374333
Name: Population_2011, dtype: int64

In [22]:
#Merging Population and Literacy Rate on State using merge function

In [26]:
pop_df = df[["State_UT", "Population_2011"]]

In [27]:
pop_df

                       State_UT  Population_2011
0   Andaman and Nicobar Islands           380581
1                Andhra Pradesh         49386799
2             Arunachal Pradesh          1383727
3                         Assam         31205576
4                         Bihar        104099452
5                    Chandigarh          1055450
6                  Chhattisgarh         25545198
7        Dadra and Nagar Haveli           343709
8                 Daman and Diu           243247
9                         Delhi         16787941
10                          Goa          1458545
11                      Gujarat         60439692
12                      Haryana         25351462
13             Himachal Pradesh          6864602
14            Jammu and Kashmir         12267013
15                    Jharkhand         32988134
16                    Karnataka         61095297
17                       Kerala         33406061
18                  Lakshadweep            64473
19               Madhya Pradesh         72626809
20                  Maharashtra        112374333
21                      Manipur          2855794
22                    Meghalaya          2966889
23                      Mizoram          1097206
24                     Nagaland          1978502
25                       Odisha         41974218
26                   Puducherry          1247953
27                       Punjab         27743338
28                    Rajasthan         68548437
29                       Sikkim           610577
30                   Tamil Nadu         72147030
31                    Telangana         35193978
32                      Tripura          3673917
33                Uttar Pradesh        199812341
34                  Uttarakhand         10086292
35                  West Bengal         91276115

In [29]:
lit_df = df[["State_UT", "Literacy_Rate_2011"]]

In [30]:
lit_df

                       State_UT  Literacy_Rate_2011
0   Andaman and Nicobar Islands                86.3
1                Andhra Pradesh                67.7
2             Arunachal Pradesh                67.0
3                         Assam                73.2
4                         Bihar                63.8
5                    Chandigarh                86.4
6                  Chhattisgarh                71.0
7        Dadra and Nagar Haveli                77.7
8                 Daman and Diu                87.1
9                         Delhi                86.3
10                          Goa                87.4
11                      Gujarat                79.3
12                      Haryana                76.6
13             Himachal Pradesh                83.8
14            Jammu and Kashmir                68.7
15                    Jharkhand                67.6
16                    Karnataka                75.6
17                       Kerala                93.9
18                  Lakshadweep                92.3
19               Madhya Pradesh                70.6
20                  Maharashtra                82.9
21                      Manipur                79.8
22                    Meghalaya                75.5
23                      Mizoram                91.6
24                     Nagaland                80.1
25                       Odisha                73.5
26                   Puducherry                86.5
27                       Punjab                76.7
28                    Rajasthan                67.1
29                       Sikkim                82.2
30                   Tamil Nadu                80.3
31                    Telangana                66.5
32                      Tripura                87.8
33                Uttar Pradesh                69.7
34                  Uttarakhand                79.6
35                  West Bengal                77.1

In [31]:
merged_df = pd.merge(pop_df, lit_df, on = "State_UT")

In [32]:
merged_df

                       State_UT  Population_2011  Literacy_Rate_2011
0   Andaman and Nicobar Islands           380581                86.3
1                Andhra Pradesh         49386799                67.7
2             Arunachal Pradesh          1383727                67.0
3                         Assam         31205576                73.2
4                         Bihar        104099452                63.8
5                    Chandigarh          1055450                86.4
6                  Chhattisgarh         25545198                71.0
7        Dadra and Nagar Haveli           343709                77.7
8                 Daman and Diu           243247                87.1
9                         Delhi         16787941                86.3
10                          Goa          1458545                87.4
11                      Gujarat         60439692                79.3
12                      Haryana         25351462                76.6
13             Himachal Pradesh          6864602                83.8
14            Jammu and Kashmir         12267013                68.7
15                    Jharkhand         32988134                67.6
16                    Karnataka         61095297                75.6
17                       Kerala         33406061                93.9
18                  Lakshadweep            64473                92.3
19               Madhya Pradesh         72626809                70.6
20                  Maharashtra        112374333                82.9
21                      Manipur          2855794                79.8
22                    Meghalaya          2966889                75.5
23                      Mizoram          1097206                91.6
24                     Nagaland          1978502                80.1
25                       Odisha         41974218                73.5
26                   Puducherry          1247953                86.5
27                       Punjab         27743338                76.7
28                    Rajasthan         68548437                67.1
29                       Sikkim           610577                82.2
30                   Tamil Nadu         72147030                80.3
31                    Telangana         35193978                66.5
32                      Tripura          3673917                87.8
33                Uttar Pradesh        199812341                69.7
34                  Uttarakhand         10086292                79.6
35                  West Bengal         91276115                77.1

In [45]:
#Pivot_Table using populationa and calculating the mean using agg function
pivot = pd.pivot_table(
    df,
    index="Region",
    values="Population_2011",
    aggfunc="mean"
)

print(pivot)

            Population_2011
Region
Central        4.908600e+07
East           6.758448e+07
North          4.094632e+07
North East     5.721524e+06
South          3.161527e+07
West           3.497191e+07

# Export cleaned DataFrame to CSV and Parquet. Compare file sizes.

In [51]:
import os

In [48]:
# Remove rows with missing values
cleaned_df = df.dropna()

In [50]:
# Save cleaned files
cleaned_df.to_csv("india_state_2011_cleaned.csv", index=False)
cleaned_df.to_parquet("india_state_2011_cleaned.parquet", index=False)

In [53]:
# Compare file sizes
csv_size = os.path.getsize("india_state_2011_cleaned.csv")
parquet_size = os.path.getsize("india_state_2011_cleaned.parquet")

In [54]:
print("CSV size:", round(csv_size / 1024, 2), "KB")
print("Parquet size:", round(parquet_size / 1024, 2), "KB")

CSV size: 3.81 KB
Parquet size: 4.68 KB