# Load a real Indian dataset (CSV) into Pandas DataFrame. Print: shape, dtypes, head(10).

In [25]:
import pandas as pd

In [4]:
df = pd.read_csv("india_state_2011.csv")

In [9]:
df.head(10)

,State_UT,Region,Population_2011,Literacy_Rate_2011,Source
0,Andaman and Nicobar Islands,South,380581,86.3,Office of the Registrar General and Census Com...
1,Andhra Pradesh,South,49386799,67.7,Office of the Registrar General and Census Com...
2,Arunachal Pradesh,North East,1383727,67.0,Office of the Registrar General and Census Com...
3,Assam,North East,31205576,73.2,Office of the Registrar General and Census Com...
4,Bihar,East,104099452,63.8,Office of the Registrar General and Census Com...
5,Chandigarh,North,1055450,86.4,Office of the Registrar General and Census Com...
6,Chhattisgarh,Central,25545198,71.0,Office of the Registrar General and Census Com...
7,Dadra and Nagar Haveli,West,343709,77.7,Office of the Registrar General and Census Com...
8,Daman and Diu,West,243247,87.1,Office of the Registrar General and Census Com...
9,Delhi,North,16787941,86.3,Office of the Registrar General and Census Com...

In [7]:
df1 = df.drop('Source', axis = 1)

In [10]:
df1.head(10)

,State_UT,Region,Population_2011,Literacy_Rate_2011
0,Andaman and Nicobar Islands,South,380581,86.3
1,Andhra Pradesh,South,49386799,67.7
2,Arunachal Pradesh,North East,1383727,67.0
3,Assam,North East,31205576,73.2
4,Bihar,East,104099452,63.8
5,Chandigarh,North,1055450,86.4
6,Chhattisgarh,Central,25545198,71.0
7,Dadra and Nagar Haveli,West,343709,77.7
8,Daman and Diu,West,243247,87.1
9,Delhi,North,16787941,86.3

In [11]:
df2 = df.drop(['Source', 'Region'], axis = 1)

In [12]:
df2.head(10)

                      State_UT  Population_2011  Literacy_Rate_2011
0  Andaman and Nicobar Islands           380581                86.3
1               Andhra Pradesh         49386799                67.7
2            Arunachal Pradesh          1383727                67.0
3                        Assam         31205576                73.2
4                        Bihar        104099452                63.8
5                   Chandigarh          1055450                86.4
6                 Chhattisgarh         25545198                71.0
7       Dadra and Nagar Haveli           343709                77.7
8                Daman and Diu           243247                87.1
9                        Delhi         16787941                86.3

In [14]:
df1.shape

(36, 4)

In [15]:
df2. shape

(36, 3)

In [21]:
df1.dtypes

State_UT                  str
Region                    str
Population_2011         int64
Literacy_Rate_2011    float64
dtype: object

In [23]:
print(df["State_UT"].dtype)

str

In [24]:
print(df2.dtypes)

State_UT                  str
Population_2011         int64
Literacy_Rate_2011    float64
dtype: object